<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('products', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('sku')->nullable()->unique(); $t->string('barcode')->nullable()->index(); $t->string('category')->nullable(); $t->string('brand')->nullable(); $t->text('description')->nullable(); $t->decimal('buying_price', 12, 2)->default(0); $t->decimal('selling_price', 12, 2)->default(0); $t->unsignedInteger('stock')->default(0); $t->unsignedInteger('reorder_level')->default(0); $t->string('image_url')->nullable(); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('suppliers', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('phone')->nullable(); $t->string('email')->nullable(); $t->text('address')->nullable(); $t->text('notes')->nullable(); $t->timestamps(); });
        Schema::create('resellers', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('phone')->nullable(); $t->string('email')->nullable(); $t->text('notes')->nullable(); $t->timestamps(); });
        Schema::create('orders', function (Blueprint $t) { $t->id(); $t->string('order_number')->unique(); $t->string('customer_name')->nullable(); $t->string('customer_phone')->nullable(); $t->decimal('subtotal', 12, 2)->default(0); $t->decimal('discount', 12, 2)->default(0); $t->decimal('tax', 12, 2)->default(0); $t->decimal('total', 12, 2)->default(0); $t->enum('payment_method', ['cash','mpesa','card','bank'])->default('cash'); $t->text('notes')->nullable(); $t->foreignId('attendant_id')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); });
        Schema::create('order_items', function (Blueprint $t) { $t->id(); $t->foreignId('order_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->nullable()->constrained()->nullOnDelete(); $t->string('name_snapshot'); $t->unsignedInteger('quantity'); $t->decimal('unit_price', 12, 2); $t->decimal('buying_price_snapshot', 12, 2)->default(0); $t->decimal('line_total', 12, 2); $t->timestamp('created_at')->useCurrent(); });
        Schema::create('stock_intakes', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->restrictOnDelete(); $t->foreignId('supplier_id')->nullable()->constrained()->nullOnDelete(); $t->string('prefix')->nullable(); $t->unsignedInteger('quantity'); $t->date('intake_date'); $t->text('notes')->nullable(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); });
        Schema::create('reseller_takeouts', function (Blueprint $t) { $t->id(); $t->foreignId('reseller_id')->constrained()->restrictOnDelete(); $t->date('takeout_date'); $t->text('notes')->nullable(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); });
        Schema::create('product_serials', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->restrictOnDelete(); $t->string('prefix')->nullable(); $t->string('serial_suffix'); $t->string('serial'); $t->foreignId('supplier_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('intake_id')->nullable()->constrained('stock_intakes')->nullOnDelete(); $t->enum('status', ['in_stock','with_reseller','sold','returned_to_supplier'])->default('in_stock'); $t->foreignId('reseller_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('takeout_id')->nullable()->constrained('reseller_takeouts')->nullOnDelete(); $t->foreignId('order_id')->nullable()->constrained()->nullOnDelete(); $t->timestamp('sold_at')->nullable(); $t->text('notes')->nullable(); $t->timestamps(); $t->unique(['product_id', 'serial']); $t->index(['product_id', 'status']); });
    }
    public function down(): void { foreach (['product_serials','reseller_takeouts','stock_intakes','order_items','orders','resellers','suppliers','products'] as $table) Schema::dropIfExists($table); }
};
