<div class="space-y-6" x-data="{ supplierFiltersOpen: false }">
    <div class="flex flex-wrap items-end justify-between gap-4">
        <div><h1 class="text-2xl font-bold text-ink sm:text-3xl">Financial reports</h1><p class="text-sm text-slate-500">{{ $periodLabel }}</p></div>
        <div class="flex flex-wrap items-end gap-2">
            <div><label class="label">Time period</label><select wire:model.live="period" class="input w-40"><option value="1">Today</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last 12 months</option><option value="all">All time</option><option value="custom">Custom dates</option></select></div>
            @if($period==='custom')
                <div><label class="label">From</label><input wire:model="startDate" type="date" class="input w-40">@error('startDate')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="label">To</label><input wire:model="endDate" type="date" class="input w-40">@error('endDate')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <button wire:click="applyCustomPeriod" class="btn-primary">Apply</button>
            @endif
        </div>
    </div>

    <div class="grid grid-cols-2 gap-3 lg:grid-cols-4">
        @foreach([['Revenue',$revenue,'trending-up','text-green-700'],['Expenses',$expensesTotal,'wallet-cards','text-brand-700'],['Sold buying cost',$soldBuyingPrice,'package-check','text-ink'],['Profit',$profit,'chart-no-axes-combined',$profit>=0?'text-green-700':'text-red-700']] as [$label,$value,$icon,$color])
            <article class="card p-4 sm:p-5"><div class="flex items-center justify-between gap-2"><p class="text-[10px] font-semibold uppercase tracking-wider text-slate-500 sm:text-xs">{{ $label }}</p><i data-lucide="{{ $icon }}" class="size-4 text-slate-400"></i></div><p class="mt-2 truncate text-lg font-bold {{ $color }} sm:text-2xl" title="KES {{ number_format($value,2) }}">KES {{ number_format($value,2) }}</p></article>
        @endforeach
    </div>

    <div class="grid gap-4 lg:grid-cols-3">
        <section class="card p-5 lg:col-span-2">
            <div class="flex items-center justify-between"><div><h2 class="font-bold">Revenue and expenses</h2><p class="text-xs text-slate-500">{{ $chart['caption'] }}</p></div><div class="flex gap-3 text-xs"><span class="flex items-center gap-1"><i class="size-2.5 rounded-sm bg-ink"></i>Revenue</span><span class="flex items-center gap-1"><i class="size-2.5 rounded-sm bg-brand-500"></i>Expenses</span></div></div>
            @php($chartMax=max(1, ...$chart['salesData'], ...$chart['expenseData']))
            <div class="mt-5 overflow-x-auto pb-2"><div class="flex h-56 min-w-[640px] items-end gap-1.5 border-b border-slate-200 px-1">@foreach($chart['labels'] as $index=>$label)<div class="group flex h-full min-w-7 flex-1 flex-col justify-end" title="{{ $label }} · Revenue KES {{ number_format($chart['salesData'][$index],2) }} · Expenses KES {{ number_format($chart['expenseData'][$index],2) }}"><div class="flex h-[calc(100%-1.4rem)] items-end justify-center gap-0.5"><span class="w-2 rounded-t bg-ink" style="height:{{ max(1,($chart['salesData'][$index]/$chartMax)*100) }}%"></span><span class="w-2 rounded-t bg-brand-500" style="height:{{ max(1,($chart['expenseData'][$index]/$chartMax)*100) }}%"></span></div><small class="mt-1 block truncate text-center text-[8px] text-slate-400">{{ $label }}</small></div>@endforeach</div></div>
        </section>

        <section class="card p-5"><h2 class="font-bold">Sales sources</h2><p class="text-xs text-slate-500">Orders by customer source.</p>@php($sourceMax=max(1,(int)$sources->max('orders_count'))) <div class="mt-5 space-y-4">@forelse($sources as $source)<div><div class="mb-1 flex justify-between gap-3 text-xs"><b class="capitalize">{{ str_replace('_',' ',$source->customer_source) }}</b><span>{{ $source->orders_count }} orders · KES {{ number_format($source->revenue,2) }}</span></div><div class="h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-brand-500" style="width:{{ ($source->orders_count/$sourceMax)*100 }}%"></div></div></div>@empty<div class="py-10 text-center text-sm text-slate-500">No sales in this period.</div>@endforelse</div></section>
    </div>

    <section class="card overflow-hidden">
        @php($supplierFilterCount=collect([$supplierId,count($productIds)?'products':null,$inventoryState,$paymentStatus,$period!=='30'?$period:null])->filter()->count())
        <div class="flex items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h2 class="font-bold">Supplier records</h2><p class="text-xs text-slate-500">Buying costs, payments, and unpaid value by serial.</p></div><button type="button" @click="supplierFiltersOpen = true" class="btn-muted relative shrink-0 gap-2 px-3"><i data-lucide="list-filter" class="size-4"></i>Filters @if($supplierFilterCount)<span class="grid size-5 place-items-center rounded-full bg-brand-600 text-[10px] text-white">{{ $supplierFilterCount }}</span>@endif</button></div>
        @if($supplierStats)
            <div class="grid grid-cols-2 gap-3 p-5 lg:grid-cols-6"><div class="rounded-xl bg-ink p-3 text-white"><small class="text-slate-300">Total worth</small><b class="mt-1 block">KES {{ number_format($supplierStats->total_worth,2) }}</b></div><div class="rounded-xl bg-slate-50 p-3"><small class="text-slate-500">Total units</small><b class="mt-1 block">{{ number_format($supplierStats->total_units) }}</b></div><div class="rounded-xl bg-green-50 p-3"><small class="text-green-700">Total paid</small><b class="mt-1 block text-green-800">KES {{ number_format($supplierStats->total_paid,2) }}</b></div><div class="rounded-xl bg-red-50 p-3"><small class="text-red-600">Total unpaid</small><b class="mt-1 block text-red-700">KES {{ number_format($supplierStats->total_unpaid,2) }}</b></div><div class="rounded-xl bg-slate-50 p-3"><small class="text-slate-500">In-stock worth</small><b class="mt-1 block">KES {{ number_format($supplierStats->instock_worth,2) }}</b></div><div class="rounded-xl bg-brand-50 p-3"><small class="text-brand-700">Take-out worth</small><b class="mt-1 block text-brand-700">KES {{ number_format($supplierStats->takeout_worth,2) }}</b></div></div>
            <div class="w-full overflow-hidden border-t border-slate-100"><table class="w-full table-fixed text-xs sm:table-auto sm:text-sm"><thead class="table-head"><tr><th class="w-[34%] px-4 py-3 sm:w-auto sm:px-5">Product / Serial</th><th class="w-[22%]">State</th><th class="hidden text-right sm:table-cell">Buying price</th><th class="w-[22%] text-right">Paid</th><th class="w-[22%] pr-4 text-right sm:pr-5">Unpaid</th></tr></thead><tbody class="divide-y">@forelse($supplierRecords as $record)@php($unpaid=max(0,(float)$record->buying_price-(float)$record->paid))<tr><td class="px-4 py-3 sm:px-5"><b class="block truncate" title="{{ $record->product_name }}">{{ $record->product_name }}</b><code class="block truncate text-[10px] text-slate-500">{{ $record->serial }}</code></td><td><span class="block truncate capitalize">{{ str_replace('_',' ',$record->status) }}</span></td><td class="hidden whitespace-nowrap text-right sm:table-cell">KES {{ number_format($record->buying_price,2) }}</td><td class="whitespace-nowrap text-right font-semibold text-green-700">{{ number_format($record->paid,2) }}</td><td class="whitespace-nowrap pr-4 text-right font-semibold text-red-700 sm:pr-5">{{ number_format($unpaid,2) }}</td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-slate-500">No supplier records match these filters.</td></tr>@endforelse</tbody></table></div>
            <div class="p-4">{{ $supplierRecords->links() }}</div>
        @else
            <div class="p-10 text-center"><i data-lucide="truck" class="mx-auto size-8 text-slate-300"></i><p class="mt-2 text-sm text-slate-500">Use Filters and select a supplier to display records and statistics.</p></div>
        @endif
    </section>

    <div x-cloak x-show="supplierFiltersOpen" x-transition.opacity @keydown.escape.window="supplierFiltersOpen = false" @click.self="supplierFiltersOpen = false" class="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/55 p-4">
        <section class="my-auto flex max-h-[calc(100vh-2rem)] w-full max-w-lg flex-col overflow-hidden rounded-2xl bg-white shadow-2xl">
            <div class="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 class="font-bold">Filter supplier records</h2><p class="text-xs text-slate-500">All statistics update from these filters.</p></div><button type="button" @click="supplierFiltersOpen = false" class="grid size-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-100"><i data-lucide="x" class="size-5"></i></button></div>
            <div class="flex-1 space-y-5 overflow-y-auto p-5">
                <div><label class="label">Supplier</label><select wire:model.live="supplierId" class="input"><option value="">Select supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select>@error('supplierId')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div><div class="mb-1.5 flex items-center justify-between"><label class="label mb-0">Products</label>@if(count($productIds))<button type="button" wire:click="$set('productIds', [])" class="text-xs font-semibold text-brand-700">Clear products</button>@endif</div>@if(!$supplierId)<div class="rounded-xl border border-dashed p-4 text-center text-xs text-slate-500">Select a supplier first.</div>@else<div class="grid max-h-40 grid-cols-1 gap-1 overflow-y-auto rounded-xl border border-slate-200 bg-slate-50 p-1.5 sm:grid-cols-2">@forelse($supplierProducts as $product)<label class="flex min-w-0 cursor-pointer items-center gap-2 rounded-lg bg-white px-2.5 py-2 text-xs shadow-sm hover:bg-brand-50"><input wire:model.live="productIds" type="checkbox" value="{{ $product->id }}" class="size-4 shrink-0 rounded border-slate-300 text-brand-600"><span class="truncate" title="{{ $product->name }}">{{ $product->name }}</span></label>@empty<div class="col-span-full p-4 text-center text-xs text-slate-500">No priced products for this supplier.</div>@endforelse</div>@endif @error('productIds.*')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div class="grid gap-4 sm:grid-cols-2"><div><label class="label">Inventory state</label><select wire:model.live="inventoryState" class="input"><option value="">All states</option><option value="in_stock">In stock</option><option value="with_reseller">Take-out</option><option value="sold">Sold</option><option value="returned_to_supplier">Returned to supplier</option></select></div><div><label class="label">Payment status</label><select wire:model.live="paymentStatus" class="input"><option value="">All statuses</option><option value="unpaid">Unpaid</option><option value="partial">Partially paid</option><option value="paid">Paid</option></select></div></div>
                <div><label class="label">Time period</label><select wire:model.live="period" class="input"><option value="1">Today</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last 12 months</option><option value="all">All time</option><option value="custom">Custom dates</option></select></div>
                @if($period==='custom')<div class="grid grid-cols-2 gap-3"><div><label class="label">From</label><input wire:model="startDate" type="date" class="input">@error('startDate')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div><label class="label">To</label><input wire:model="endDate" type="date" class="input">@error('endDate')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div></div>@endif
            </div>
            <div class="flex justify-end gap-2 border-t border-slate-100 p-5"><button type="button" @click="$wire.clearSupplierFilters().then(() => supplierFiltersOpen = false)" class="btn-muted">Clear</button><button type="button" @click="$wire.applySupplierFilters().then(() => supplierFiltersOpen = false)" class="btn-primary">Apply filters</button></div>
        </section>
    </div>

    <section class="card overflow-hidden">
        <div class="border-b border-slate-100 p-5"><h2 class="font-bold">Financial records</h2><p class="text-xs text-slate-500">Sales, expenses, and supplier payments for this period.</p></div>
        <div class="w-full overflow-hidden"><table class="w-full table-fixed text-xs sm:table-auto sm:text-sm"><thead class="table-head"><tr><th class="w-[38%] px-4 py-3 sm:w-auto sm:px-5">Record</th><th class="hidden sm:table-cell">Date</th><th class="hidden md:table-cell">Description</th><th class="w-[31%] text-right sm:w-auto">In</th><th class="w-[31%] pr-4 text-right sm:w-auto sm:pr-5">Out</th></tr></thead><tbody class="divide-y">@forelse($records as $record)<tr><td class="px-4 py-3 sm:px-5"><b class="block truncate">{{ $record->reference }}</b><small class="capitalize text-slate-500">{{ str_replace('_',' ',$record->record_type) }}</small></td><td class="hidden whitespace-nowrap sm:table-cell">{{ \Carbon\Carbon::parse($record->happened_at)->format('d M Y H:i') }}</td><td class="hidden max-w-xs truncate md:table-cell">{{ $record->description }}</td><td class="whitespace-nowrap text-right font-semibold text-green-700">{{ $record->inflow>0?'KES '.number_format($record->inflow,2):'—' }}</td><td class="whitespace-nowrap pr-4 text-right font-semibold text-red-700 sm:pr-5">{{ $record->outflow>0?'KES '.number_format($record->outflow,2):'—' }}</td></tr>@empty<tr><td colspan="5" class="py-12 text-center text-slate-500">No financial records in this period.</td></tr>@endforelse</tbody></table></div>
        <div class="p-4">{{ $records->links() }}</div>
    </section>
</div>
