<div class="space-y-6">
    <div class="flex flex-nowrap items-center justify-between gap-3"><div class="min-w-0"><h1 class="text-2xl font-bold text-ink sm:text-3xl">Suppliers</h1><p class="truncate text-xs text-slate-500 sm:text-sm">Manage the businesses that supply your stock.</p></div><button wire:click="create" class="btn-primary shrink-0 gap-2"><i data-lucide="plus" class="size-4"></i>Add supplier</button></div>
    <section class="card p-5">
        <input wire:model.live.debounce.300ms="search" class="input mb-4 max-w-md" placeholder="Search name, phone or email">
        <div class="overflow-x-auto"><table class="w-full text-sm"><thead class="table-head"><tr><th class="py-3">Supplier</th><th class="hidden sm:table-cell">Phone</th><th class="hidden md:table-cell">Email</th><th class="text-right">Action</th></tr></thead><tbody class="divide-y">@forelse($suppliers as $supplier)<tr><td class="min-w-0 py-3 pr-3"><b class="block max-w-[12rem] truncate sm:max-w-xs" title="{{ $supplier->name }}">{{ $supplier->name }}</b><span class="text-xs text-slate-500 sm:hidden">{{ $supplier->phone?:'No phone' }}</span></td><td class="hidden sm:table-cell">{{ $supplier->phone?:'—' }}</td><td class="hidden md:table-cell">{{ $supplier->email?:'—' }}</td><td class="text-right"><button wire:click="edit({{ $supplier->id }})" class="font-semibold text-brand-600"><i data-lucide="pencil" class="mr-1 inline size-3.5"></i>Edit</button></td></tr>@empty<tr><td colspan="4" class="py-12 text-center text-slate-500">No suppliers found.</td></tr>@endforelse</tbody></table></div>
        <div class="mt-4">{{ $suppliers->links() }}</div>
    </section>
    @if($showForm)<div wire:click.self="cancel" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form wire:submit="save" class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div class="mb-5 flex justify-between"><div><h2 class="text-xl font-bold">{{ $editing?'Edit supplier':'Add supplier' }}</h2><p class="text-sm text-slate-500">Only the supplier name is required.</p></div><button type="button" wire:click="cancel" class="text-2xl text-slate-400"><i data-lucide="x" class="size-5"></i></button></div><div class="space-y-4"><div><label class="label">Name</label><input wire:model="name" class="input" required autofocus>@error('name')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div class="grid gap-4 sm:grid-cols-2"><div><label class="label">Phone <span class="normal-case text-slate-400">(optional)</span></label><input wire:model="phone" class="input" type="tel"></div><div><label class="label">Email <span class="normal-case text-slate-400">(optional)</span></label><input wire:model="email" class="input" type="email">@error('email')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div></div><div><label class="label">Address <span class="normal-case text-slate-400">(optional)</span></label><textarea wire:model="address" class="input min-h-20"></textarea></div></div><div class="mt-7 flex justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" wire:click="cancel" class="btn-muted">Cancel</button><button class="btn-primary">{{ $editing?'Save changes':'Add supplier' }}</button></div></form></div>@endif
</div>
